---
env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends:
- airbnb
- eslint:recommended
- plugin:react/recommended
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 8
  sourceType: module
plugins:
- babel
- react
- typescript
rules:
  babel/semi: 0
  import/no-extraneous-dependencies: 0
  import/no-useless-path-segments: 2
  indent:
  - error
  - 2
  - SwitchCase: 1
  linebreak-style:
  - error
  - unix
  no-console: 0
  quotes:
  - error
  - single
  react/destructuring-assignment: 2
  react/forbid-prop-types:
  - 0
  react/jsx-filename-extension:
  - 0
  react/jsx-max-props-per-line:
  - 0
  react/jsx-sort-props:
  - 1
  react/jsx-wrap-multilines:
  - 1
  - arrow: parens-new-line
    assignment: parens-new-line
    condition: parens-new-line
    declaration: parens-new-line
    logical: parens
    prop: parens-new-line
    return: parens-new-line
  react/no-array-index-key:
  - 0
  react/no-unused-state:
  - 1
  react/prefer-stateless-function: 'off'
  react/prop-types:
  - 1
  react/require-default-props:
  - 1
  react/sort-comp: 0
  semi:
  - error
  - always
