const CLOSE_LIBRARY =       'CLOSE_LIBRARY';
const DISABLE_LOADING =     'DISABLE_LOADING';
const ENABLE_LOADING =      'ENABLE_LOADING';
const OPEN_COMIC =          'OPEN_COMIC';
const OPEN_LIBRARY =        'OPEN_LIBRARY';
const SET_CONTENT =         'SET_CONTENT';
const SET_IMAGES =          'SET_IMAGES';
const SET_ZOOM_LEVEL =      'SET_ZOOM_LEVEL';
const TOGGLE_LIBRARY =      'TOGGLE_LIBRARY';
const TOGGLE_PAGE_COUNT =   'TOGGLE_PAGE_COUNT';
const TURN_PAGE =           'TURN_PAGE';
const TURN_PAGE_LEFT =      'TURN_PAGE_LEFT';
const TURN_PAGE_RIGHT =     'TURN_PAGE_RIGHT';

export {
  CLOSE_LIBRARY,
  DISABLE_LOADING,
  ENABLE_LOADING,
  OPEN_COMIC,
  OPEN_LIBRARY,
  SET_CONTENT,
  SET_IMAGES,
  SET_ZOOM_LEVEL,
  TOGGLE_LIBRARY,
  TOGGLE_PAGE_COUNT,
  TURN_PAGE,
  TURN_PAGE_LEFT,
  TURN_PAGE_RIGHT,
};
